
POST https://barber-api-2tgx.onrender.com/auth/signup
Content-Type: application/json

{
    "username":"Kon",
    "email":"konsona@gmail.com",
    "phoneNumber":"0920079070",
    "location":"Juba",
    "imageUrl":"image-url",
    "password":"konsonak",
    "billingInformation":{},
    "purchaseHistory":{}

}

###
GET http://localhost:3001/users
