
POST https://barber-api-2tgx.onrender.com/auth/login
Content-Type: application/json

{
    "username":"Kon",
    "email":"konsonak@gmail.com",
    "phoneNumber":"0920079070",
    "location":"Juba",
    "imageUrl":"image-url",
    "password":"konsonak"
}